export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const MAINPAGE_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const BOOKPAGE_ROUTE = '/bookpage'
export const CONTACT_ROUTE = '/contact'